AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Hypertrace Node Lambda layer
Parameters:
  LayerName:
    Type: String
    Description: Lambda layer name to be published
    Default: hypertrace-layer-node
Resources:
  HypertraceLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: Hypertrace node layer
      ContentUri: './build/layer'
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs12.x
        - nodejs10.x
      LicenseInfo: 'Available under the Apache-2.0 license.'
      RetentionPolicy: Retain