name: Pr build
on:
  pull_request:
  push:
    branches: [main]


jobs:
  test:
    strategy:
      matrix:
        node_version: [ "8", "10", "12", "14", "16" ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Standup Test Docker Services
        run: cd ./test/externalServices && docker-compose up -d
      - name: Wait for Docker
        run: sleep 100
      - name: Install codecov
        run: npm install codecov -g
      - name: Run Tests With Coverage
        run: npm run coverage

      - name: Upload coverage # only upload results from 1 matrix version, not all
        if: matrix.node_version == '16'
        run: codecov --token="${{ secrets.CODECOV_TOKEN }}"
