name: Publish
on:
  push:
    branches: [main]
jobs:
  generate_proto:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run generate_pb

      - name: Cache proto
        uses: actions/upload-artifact@v2
        with:
          name: proto
          path: ./src/config/generated.*

  build:
    runs-on: ubuntu-20.04
    needs: generate_proto
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install

      - uses: actions/download-artifact@v2
        with:
          name: proto
          path: ./src/config/

      - run: tsc

      - name: Generate release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./hypertrace-nodejsagent-*.tgz